# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from immu.schema import schema_pb2 as schema__pb2


class ImmuServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Set = channel.unary_unary(
        '/immudb.schema.ImmuService/Set',
        request_serializer=schema__pb2.KeyValue.SerializeToString,
        response_deserializer=schema__pb2.Index.FromString,
        )
    self.SafeSet = channel.unary_unary(
        '/immudb.schema.ImmuService/SafeSet',
        request_serializer=schema__pb2.SafeSetOptions.SerializeToString,
        response_deserializer=schema__pb2.Proof.FromString,
        )
    self.SetBatch = channel.unary_unary(
        '/immudb.schema.ImmuService/SetBatch',
        request_serializer=schema__pb2.KVList.SerializeToString,
        response_deserializer=schema__pb2.Index.FromString,
        )
    self.Get = channel.unary_unary(
        '/immudb.schema.ImmuService/Get',
        request_serializer=schema__pb2.Key.SerializeToString,
        response_deserializer=schema__pb2.Item.FromString,
        )
    self.SafeGet = channel.unary_unary(
        '/immudb.schema.ImmuService/SafeGet',
        request_serializer=schema__pb2.SafeGetOptions.SerializeToString,
        response_deserializer=schema__pb2.SafeItem.FromString,
        )
    self.GetBatch = channel.unary_unary(
        '/immudb.schema.ImmuService/GetBatch',
        request_serializer=schema__pb2.KeyList.SerializeToString,
        response_deserializer=schema__pb2.ItemList.FromString,
        )
    self.Scan = channel.unary_unary(
        '/immudb.schema.ImmuService/Scan',
        request_serializer=schema__pb2.ScanOptions.SerializeToString,
        response_deserializer=schema__pb2.ItemList.FromString,
        )
    self.Count = channel.unary_unary(
        '/immudb.schema.ImmuService/Count',
        request_serializer=schema__pb2.KeyPrefix.SerializeToString,
        response_deserializer=schema__pb2.ItemsCount.FromString,
        )
    self.CurrentRoot = channel.unary_unary(
        '/immudb.schema.ImmuService/CurrentRoot',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=schema__pb2.Root.FromString,
        )
    self.Inclusion = channel.unary_unary(
        '/immudb.schema.ImmuService/Inclusion',
        request_serializer=schema__pb2.Index.SerializeToString,
        response_deserializer=schema__pb2.InclusionProof.FromString,
        )
    self.Consistency = channel.unary_unary(
        '/immudb.schema.ImmuService/Consistency',
        request_serializer=schema__pb2.Index.SerializeToString,
        response_deserializer=schema__pb2.ConsistencyProof.FromString,
        )
    self.ByIndex = channel.unary_unary(
        '/immudb.schema.ImmuService/ByIndex',
        request_serializer=schema__pb2.Index.SerializeToString,
        response_deserializer=schema__pb2.Item.FromString,
        )
    self.History = channel.unary_unary(
        '/immudb.schema.ImmuService/History',
        request_serializer=schema__pb2.Key.SerializeToString,
        response_deserializer=schema__pb2.ItemList.FromString,
        )
    self.Health = channel.unary_unary(
        '/immudb.schema.ImmuService/Health',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=schema__pb2.HealthResponse.FromString,
        )


class ImmuServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Set(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SafeSet(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetBatch(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Get(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SafeGet(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetBatch(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Scan(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Count(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CurrentRoot(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Inclusion(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Consistency(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ByIndex(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def History(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Health(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ImmuServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Set': grpc.unary_unary_rpc_method_handler(
          servicer.Set,
          request_deserializer=schema__pb2.KeyValue.FromString,
          response_serializer=schema__pb2.Index.SerializeToString,
      ),
      'SafeSet': grpc.unary_unary_rpc_method_handler(
          servicer.SafeSet,
          request_deserializer=schema__pb2.SafeSetOptions.FromString,
          response_serializer=schema__pb2.Proof.SerializeToString,
      ),
      'SetBatch': grpc.unary_unary_rpc_method_handler(
          servicer.SetBatch,
          request_deserializer=schema__pb2.KVList.FromString,
          response_serializer=schema__pb2.Index.SerializeToString,
      ),
      'Get': grpc.unary_unary_rpc_method_handler(
          servicer.Get,
          request_deserializer=schema__pb2.Key.FromString,
          response_serializer=schema__pb2.Item.SerializeToString,
      ),
      'SafeGet': grpc.unary_unary_rpc_method_handler(
          servicer.SafeGet,
          request_deserializer=schema__pb2.SafeGetOptions.FromString,
          response_serializer=schema__pb2.SafeItem.SerializeToString,
      ),
      'GetBatch': grpc.unary_unary_rpc_method_handler(
          servicer.GetBatch,
          request_deserializer=schema__pb2.KeyList.FromString,
          response_serializer=schema__pb2.ItemList.SerializeToString,
      ),
      'Scan': grpc.unary_unary_rpc_method_handler(
          servicer.Scan,
          request_deserializer=schema__pb2.ScanOptions.FromString,
          response_serializer=schema__pb2.ItemList.SerializeToString,
      ),
      'Count': grpc.unary_unary_rpc_method_handler(
          servicer.Count,
          request_deserializer=schema__pb2.KeyPrefix.FromString,
          response_serializer=schema__pb2.ItemsCount.SerializeToString,
      ),
      'CurrentRoot': grpc.unary_unary_rpc_method_handler(
          servicer.CurrentRoot,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=schema__pb2.Root.SerializeToString,
      ),
      'Inclusion': grpc.unary_unary_rpc_method_handler(
          servicer.Inclusion,
          request_deserializer=schema__pb2.Index.FromString,
          response_serializer=schema__pb2.InclusionProof.SerializeToString,
      ),
      'Consistency': grpc.unary_unary_rpc_method_handler(
          servicer.Consistency,
          request_deserializer=schema__pb2.Index.FromString,
          response_serializer=schema__pb2.ConsistencyProof.SerializeToString,
      ),
      'ByIndex': grpc.unary_unary_rpc_method_handler(
          servicer.ByIndex,
          request_deserializer=schema__pb2.Index.FromString,
          response_serializer=schema__pb2.Item.SerializeToString,
      ),
      'History': grpc.unary_unary_rpc_method_handler(
          servicer.History,
          request_deserializer=schema__pb2.Key.FromString,
          response_serializer=schema__pb2.ItemList.SerializeToString,
      ),
      'Health': grpc.unary_unary_rpc_method_handler(
          servicer.Health,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=schema__pb2.HealthResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'immudb.schema.ImmuService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
